const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#E4E4E4',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#fff',
    background: '#364248',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  tabIconDefault: '#ccc',
  tabIconSelected: tintColorLight,
  tabBar: '#fefefe',
  error: '#FF6700',
  errorDark: '#C85100',
  errorLight: '#FF832E',
  errorText: '#fff',
  warning: '#FFCC00',
  warningDark: '#C8A000',
  warningLight: '#FFD62E',
  warningText: '#666804',
  noticeBackground: tintColorLight,
  noticeText: '#fff',
  primary: '#0d46a0',
  primaryDark: '#002071',
  primaryLight: '#5471d2',
  text: 'rgba(40,40,40,1)',
  textSecondary: 'rgba(60,60,60,1)',
  textDark: 'rgba(38,38,38,1)',
  textLight: 'rgba(210,210,210,1)',
  secondary: '#4db6ac',
  secondaryDark: '#00867d',
  secondaryLight: '#82e9de',
  secondaryLightest: '#d5edeb',
};
